export interface Contact {
  id: number
  firstName: string
  lastName: string
  phone: string | null
  email: string | null
  photoUrl: string | null
  organization: string | null
  title: string | null
  location: string | null
  linkedinUrl: string | null
  twitterUrl: string | null
  website: string | null
  notes: string | null
  lastContactedAt: string | null
  createdAt: string
  updatedAt: string
  tags?: ContactTag[]
  groups?: ContactGroup[]
  notableDates?: NotableDate[]
  reminders?: Reminder[]
}

export interface Tag {
  id: number
  name: string
  color: string
  autoGenerated: boolean
  createdAt: string
  _count?: { contacts: number }
}

export interface ContactTag {
  contactId: number
  tagId: number
  assignedAt: string
  tag: Tag
}

export interface Group {
  id: number
  name: string
  description: string | null
  createdAt: string
  _count?: { contacts: number }
}

export interface ContactGroup {
  contactId: number
  groupId: number
  assignedAt: string
  group: Group
}

export type InteractionType =
  | 'CALL_INBOUND' | 'CALL_OUTBOUND' | 'CALL_MISSED'
  | 'TEXT_INBOUND' | 'TEXT_OUTBOUND'
  | 'EMAIL_INBOUND' | 'EMAIL_OUTBOUND'
  | 'MEETING' | 'MAIL_SENT' | 'MAIL_RECEIVED' | 'NOTE' | 'OTHER'

export type InteractionSource = 'MANUAL' | 'IMPORT_IOS' | 'IMPORT_ANDROID' | 'IMPORT_EMAIL' | 'API'

export interface Interaction {
  id: number
  contactId: number
  type: InteractionType
  content: string | null
  durationSeconds: number | null
  occurredAt: string
  source: InteractionSource
  createdAt: string
  contact?: { id: number; firstName: string; lastName: string }
}

export interface Reminder {
  id: number
  contactId: number
  remindAt: string
  note: string | null
  completed: boolean
  createdAt: string
  updatedAt: string
  contact?: { id: number; firstName: string; lastName: string }
}

export type NotableDateType = 'BIRTHDAY' | 'ANNIVERSARY' | 'FIRST_MET' | 'ELECTION' | 'CUSTOM'

export interface NotableDate {
  id: number
  contactId: number
  type: NotableDateType
  label: string | null
  month: number
  day: number
  year: number | null
  recurring: boolean
  notes: string | null
  createdAt: string
  // From raw query joins
  first_name?: string
  last_name?: string
  contact_id?: number
}

export interface DashboardData {
  needsAttention: Contact[]
  upcomingReminders: Reminder[]
  upcomingDates: NotableDate[]
  recentActivity: Interaction[]
  stats: {
    totalContacts: number
    interactionsThisWeek: number
    interactionsThisMonth: number
  }
}

export interface PaginatedResponse<T> {
  data: T[]
  meta: {
    page: number
    limit: number
    total: number
    totalPages: number
  }
}

export interface ContactFilters {
  search?: string
  tagIds?: number[]
  groupId?: number
  sort?: string
  needsAttention?: boolean
  page?: number
  limit?: number
}
